### ISSUE TITLE
is this working ?

### ISSUE THREAD

**Issue by vince62s** [DeadAt0m/adafactor-pytorch#1]
Hi,
trying to use this code for NMT.

I am getting a float non callable error whatever I take for lr (float or function)

here: https://github.com/DeadAt0m/adafactor-pytorch/blob/master/adafactor.py#L140

**Comment by DeadAt0m** [comment]
Hi and thank you for making me come back to this code. 

I have fixed some dirty code in __init__, so now it should work properly, check it in last commit.

**Comment by vince62s** [comment]
nope:
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/utils/optimizers.py", line 373, in step
    lr_t = group['lr'](state['step'])
TypeError: 'float' object is not callable

I am confused, may doing something wrong, but what type is group['lr'] supposed to be if not a float ?

**Comment by vince62s** [comment]
found the issue, it's ok.
